name: Update Pixiv Daily

on:
  schedule:
    - cron: '0 18 * * *' # 每天UTC时间10点运行（北京时间18点）
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Run Pixiv Script
        env:
          PIXIV_COOKIE: ${{ secrets.PIXIV_COOKIE }}
        run: node scripts/pixiv-daily.js
        
      - name: Deploy Hexo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          npm run deploy
